
name: Build Debug APK - Familyride
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      - name: Get dependencies
        run: flutter pub get
        working-directory: flutter_app
      - name: Generate icons and splash
        run: |
          flutter pub run flutter_launcher_icons
          flutter pub run flutter_native_splash:create
        working-directory: flutter_app
      - name: Build debug APK
        run: flutter build apk --debug
        working-directory: flutter_app
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Familyride-debug-apk
          path: flutter_app/build/app/outputs/flutter-apk/app-debug.apk
